tasks:
   - name: env-setup
#     init: |
#       pyenv install 3.11 -y
#       pyenv global 3.11
#       pip install numpy pandas scikit-learn seaborn jupyter
#   - name: jupyter-start
#     before: |
#       jupyter lab
